
//< !--  assembly name="EnvDTE" -->// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace KramaxAutoPilot
{
	static class Version
	{
		public const int major = 0;
		public const int minor = 3;
		public const int patch = 5;
		public const int build = 1;
		public const string Number = "0.3.5.1";
		public const string Text = Number + " Alpha";
	}
}
